// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:068e9fac-17c1-413e-bc17-6b09485a5fdb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_L5FXxZiQf",
    "aws_user_pools_web_client_id": "2vk73118rma0v8e488jv8eg7mj",
    "oauth": {},
    "aws_mobile_analytics_app_id": "6d1204b8bcdc46c1939f630aba88b048",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Contacts-envcontact",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "ApiContacts",
            "endpoint": "https://hab4ert9i9.execute-api.us-east-1.amazonaws.com/envcontact",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
